-- 코드를 입력하세요
SELECT SUBSTR(T.SALES_DATE,1,10) SALES_DATE
     , T.PRODUCT_ID
     , T.USER_ID
     , T.SALES_AMOUNT
  FROM (
        SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
          FROM ONLINE_SALE
         WHERE SUBSTR(SALES_DATE,1,7) = '2022-03'
         UNION ALL
        SELECT SALES_DATE, PRODUCT_ID, NULL USER_ID, SALES_AMOUNT
          FROM OFFLINE_SALE
         WHERE SUBSTR(SALES_DATE,1,7) = '2022-03'
       ) T
ORDER BY T.SALES_DATE, T.PRODUCT_ID, T.USER_ID
;