-- 코드를 입력하세요
SELECT T1.ANIMAL_ID
     , T1.ANIMAL_TYPE
     , T1.NAME
  FROM ANIMAL_INS T1
 INNER JOIN ANIMAL_OUTS T2
    ON T2.ANIMAL_ID = T1.ANIMAL_ID
 WHERE SUBSTR(T1.SEX_UPON_INTAKE,1,6) = 'Intact'
   AND (SUBSTR(T2.SEX_UPON_OUTCOME,1,6) = 'Spayed' OR SUBSTR(T2.SEX_UPON_OUTCOME,1,8) = 'Neutered')
 ORDER BY T1.ANIMAL_ID
   ;