-- 코드를 작성해주세요
SELECT DISTINCT T1.ID, T1.EMAIL, T1.FIRST_NAME, T1.LAST_NAME
  FROM DEVELOPERS T1
  JOIN (SELECT LENGTH(BIN(T2.CODE)) AS POS
          FROM SKILLCODES T2
         WHERE T2.CATEGORY = 'Front End') T2
 WHERE SUBSTR(BIN(T1.SKILL_CODE),T2.POS*-1,1) = '1'
 ORDER BY T1.ID
 ;