-- 코드를 입력하세요
SELECT DISTINCT T1.CAR_ID
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
 WHERE T1.START_DATE BETWEEN '2022-10-01' AND '2022-10-31'
   AND EXISTS (SELECT 'X' FROM CAR_RENTAL_COMPANY_CAR Z 
                WHERE Z.CAR_ID = T1.CAR_ID
                  AND Z.CAR_TYPE = '세단')
 ORDER BY T1.CAR_ID DESC
 ;