-- 코드를 입력하세요
SELECT CAST(SUBSTR(T1.START_DATE,6,2) AS UNSIGNED) MONTH
     , T1.CAR_ID
     , COUNT(*) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T1
 INNER JOIN (
            SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
             WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
             # WHERE SUBSTR(START_DATE,6,2) IN ('08','09','10')
             GROUP BY CAR_ID
             HAVING COUNT(CAR_ID) >= 5
            ) T2
    ON T2.CAR_ID = T1.CAR_ID
 WHERE T1.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
 GROUP BY SUBSTR(T1.START_DATE,6,2), T1.CAR_ID
 HAVING COUNT(*) > 0
 ORDER BY CAST(SUBSTR(T1.START_DATE,6,2) AS UNSIGNED), T1.CAR_ID DESC
 ;