-- 코드를 입력하세요
SELECT SUBSTR(T1.SALES_DATE, 1,4) AS YEAR
     , CAST(SUBSTR(T1.SALES_DATE, 6,2) AS UNSIGNED) AS MONTH
     , T2.GENDER
     , COUNT(DISTINCT T1.USER_ID) AS USERS
  FROM ONLINE_SALE T1
 INNER JOIN USER_INFO T2
    ON T2.USER_ID = T1.USER_ID
   AND T2.GENDER IS NOT NULL
 GROUP BY SUBSTR(T1.SALES_DATE, 1,4), SUBSTR(T1.SALES_DATE, 6,2), T2.GENDER
 ORDER BY SUBSTR(T1.SALES_DATE, 1,4), SUBSTR(T1.SALES_DATE, 6,2), T2.GENDER
 ;