-- 코드를 입력하세요
SELECT T.CAR_ID, T.CAR_TYPE, T.FEE
  FROM (
        SELECT DISTINCT T1.CAR_ID
             , T1.CAR_TYPE
             , ROUND(((100 - T3.DISCOUNT_RATE) / 100) * T1.DAILY_FEE * 30) FEE
          FROM CAR_RENTAL_COMPANY_CAR T1 
         INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
                ON T3.CAR_TYPE = T1.CAR_TYPE
               AND T3.DURATION_TYPE = '30일 이상' 
         WHERE T1.CAR_TYPE IN ('세단','SUV')
           AND T1.CAR_ID NOT IN (SELECT Z.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY Z
                                  WHERE Z.START_DATE <= '2022-11-30' AND Z.END_DATE >= '2022-11-01')
      ) T
 WHERE T.FEE >= 500000
   AND T.FEE < 2000000
 ORDER BY T.FEE DESC, T.CAR_TYPE, T.CAR_ID DESC
   ;