-- 코드를 입력하세요
WITH RECURSIVE HOUR AS (
    SELECT 0 AS HH
    UNION ALL
    SELECT HH + 1 FROM HOUR WHERE HH < 23
)
SELECT T1.HH AS HOUR
     , COUNT(T2.ANIMAL_ID) AS COUNT
  FROM HOUR T1
  LEFT JOIN ANIMAL_OUTS T2
    ON HOUR(T2.DATETIME) = T1.HH
 GROUP BY T1.HH
