-- 코드를 입력하세요
SELECT T.PRODUCT_CODE, T.SALES
  FROM (
        SELECT T2.PRODUCT_CODE
             , SUM(T2.PRICE * T1.SALES_AMOUNT) AS SALES
          FROM OFFLINE_SALE T1
         INNER JOIN PRODUCT T2
            ON T2.PRODUCT_ID = T1.PRODUCT_ID
         GROUP BY T2.PRODUCT_CODE
       ) T
 ORDER BY T.SALES DESC, T.PRODUCT_CODE