-- 코드를 입력하세요
# SELECT SUBSTR(T2.SALES_DATE,1,4)        AS YEAR
#      , SUBSTR(T2.SALES_DATE,6,2)        AS MONTH
#      , COUNT(T1.USER_ID) OVER() CNT
#   FROM USER_INFO T1
#   LEFT JOIN ONLINE_SALE T2
#     ON T2.USER_ID = T1.USER_ID
#  WHERE SUBSTR(T1.JOINED,1,4) = '2021'
#  GROUP BY SUBSTR(T2.SALES_DATE,1,4), SUBSTR(T2.SALES_DATE,6,2)

SELECT CAST(SUBSTR(T1.SALES_DATE,1,4) AS UNSIGNED)          AS YEAR
     , CAST(SUBSTR(T1.SALES_DATE,6,2) AS UNSIGNED)          AS MONTH
     , COUNT(DISTINCT T1.USER_ID)                           AS PERCHASED_USERS
     , ROUND(COUNT(DISTINCT T1.USER_ID) / T2.TOT_USER,1)    AS PUCHASED_RATIO
  FROM ONLINE_SALE T1
 INNER JOIN (
            SELECT T1.*, COUNT(*) OVER () TOT_USER
              FROM USER_INFO T1
             WHERE SUBSTR(T1.JOINED,1,4) = '2021'
            ) T2
     ON T2.USER_ID = T1.USER_ID
 GROUP BY SUBSTR(T1.SALES_DATE,1,4), SUBSTR(T1.SALES_DATE,6,2)
 ORDER BY SUBSTR(T1.SALES_DATE,1,4), SUBSTR(T1.SALES_DATE,6,2);