-- 코드를 입력하세요
SELECT T3.AUTHOR_ID
     , T3.AUTHOR_NAME
     , T2.CATEGORY
     , SUM(T1.SALES * T2.PRICE) AS TOTAL_SALES 
  FROM BOOK_SALES T1
 INNER JOIN BOOK T2
    ON T2.BOOK_ID = T1.BOOK_ID
 INNER JOIN AUTHOR T3
    ON T3.AUTHOR_ID = T2.AUTHOR_ID
 WHERE SUBSTR(T1.SALES_DATE,1,7) = '2022-01'
 GROUP BY T3.AUTHOR_ID, T3.AUTHOR_NAME, T2.CATEGORY
 ORDER BY T3.AUTHOR_ID, T2.CATEGORY DESC
 ;