-- 코드를 입력하세요
SELECT T1.APNT_NO
     , T2.PT_NAME
     , T1.PT_NO
     , T1.MCDP_CD
     , T3.DR_NAME
     , T1.APNT_YMD
  FROM APPOINTMENT T1
 INNER JOIN PATIENT T2
    ON T2.PT_NO = T1.PT_NO
 INNER JOIN DOCTOR T3
    ON T3.DR_ID = T1.MDDR_ID
 WHERE SUBSTR(T1.APNT_YMD,1,10) = '2022-04-13'
   AND T1.MCDP_CD = 'CS'
   AND T1.APNT_CNCL_YN = 'N'
 ORDER BY T1.APNT_YMD
 ;