-- 코드를 입력하세요
SELECT T2.HISTORY_ID
     , ROUND(T2.DURATION * (T1.DAILY_FEE * (100 - COALESCE(T3.DISCOUNT_RATE,0)) / 100)) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR T1
 INNER JOIN (SELECT HISTORY_ID, CAR_ID
                  , DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
                  , CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
                         THEN 90
                         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
                         THEN 30
                         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7
                         THEN 7
                         ELSE 0 END DURATION_TYPE
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            ) T2
    ON T2.CAR_ID = T1.CAR_ID
  LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN T3
    ON T3.CAR_TYPE = T1.CAR_TYPE
   AND REGEXP_SUBSTR(T3.DURATION_TYPE, '[0-9]+') = T2.DURATION_TYPE 
 WHERE T1.CAR_TYPE = '트럭'
 ORDER BY T2.DURATION * (T1.DAILY_FEE * (100 - COALESCE(T3.DISCOUNT_RATE,0)) / 100) DESC, T2.HISTORY_ID DESC
 ;