-- 코드를 입력하세요
SELECT T1.CATEGORY
     , SUM(T2.SALES) AS TOTAL_SALES 
  FROM BOOK T1
 INNER JOIN BOOK_SALES T2
    ON T2.BOOK_ID = T1.BOOK_ID
 WHERE SUBSTR(T2.SALES_DATE,1,7) = '2022-01'
 GROUP BY T1.CATEGORY
 ORDER BY T1.CATEGORY