-- 코드를 작성해주세요
SELECT T1.ID, T2.FISH_NAME, T1.LENGTH
  FROM (SELECT RANK() OVER (PARTITION BY T1.FISH_TYPE ORDER BY T1.LENGTH DESC) AS RN
             , T1.ID
             , T1.FISH_TYPE
             , T1.LENGTH
          FROM FISH_INFO T1
        ) T1
 INNER JOIN FISH_NAME_INFO T2
    ON T2.FISH_TYPE = T1.FISH_TYPE
 WHERE T1.RN = 1
 ORDER BY T1.ID