-- 코드를 작성해주세요
WITH RECURSIVE RC AS (
    SELECT 1 AS LV, PARENT_ID, ID
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
     UNION ALL
    SELECT T2.LV + 1, T1.PARENT_ID, T1.ID
      FROM ECOLI_DATA T1
     INNER JOIN RC T2
        ON T1.PARENT_ID = T2.ID
     WHERE T1.PARENT_ID IS NOT NULL
)
SELECT T.ID FROM RC T
 WHERE T.LV = 3
 ORDER BY T.ID
