-- 코드를 입력하세요
SELECT T.FLAVOR
  FROM (
        SELECT T1.FLAVOR, SUM(T1.TOTAL_ORDER + T2.TOTAL_ORDER) TOTAL_ORDER
          FROM FIRST_HALF T1
          LEFT JOIN JULY T2
            ON T2.FLAVOR = T1.FLAVOR
         GROUP BY T1.FLAVOR
         ORDER BY SUM(T1.TOTAL_ORDER + T2.TOTAL_ORDER) DESC
       ) T
 LIMIT 3
 ;
 